// Code generated by mapper, DO NOT EDIT.
package main

import (
	examples "github.com/alextanhongpin/mapper/examples"
	uuid "github.com/google/uuid"
)

type MapperImpl struct{}

func NewMapperImpl() *MapperImpl {
	return &MapperImpl{}
}

func (c *MapperImpl) mapMainAToMainB(a0 A) (B, error) {
	a0UUID, err := uuid.Parse(a0.UUID)
	if err != nil {
		return B{}, err
	}

	return B{
		ExternalID: examples.IntToString(a0.ExternalID),
		ID:         IntToString(a0.ID),
		UUID:       a0UUID,
	}, nil
}

func (c *MapperImpl) AtoB(a0 A) (B, error) {
	return c.mapMainAToMainB(a0)
}
