// Code generated by github.com/alextanhongpin/mapper, DO NOT EDIT.
package main

import examples "github.com/alextanhongpin/mapper/examples"

type MapperImpl struct {
	examplesURLBuilder *examples.URLBuilder
	uRLBuilder         *URLBuilder
}

func NewMapperImpl(examplesURLBuilder *examples.URLBuilder, uRLBuilder *URLBuilder) *MapperImpl {
	return &MapperImpl{
		examplesURLBuilder: examplesURLBuilder,
		uRLBuilder:         uRLBuilder,
	}
}

func (m *MapperImpl) mapMainAToMainB(a0 A) (B, error) {
	a0ExternalURL := m.examplesURLBuilder.Build(a0.ExternalURL)
	a0URL := m.uRLBuilder.Build(a0.URL)
	return B{
		ExternalURL: a0ExternalURL,
		URL:         a0URL,
	}, nil
}

func (m *MapperImpl) AtoB(a0 A) (B, error) {
	return m.mapMainAToMainB(a0)
}
