// Code generated by mapper, DO NOT EDIT.
package main

import examples "github.com/alextanhongpin/mapper/examples"

type MapperImpl struct {
	URLBuilder         *URLBuilder
	examplesURLBuilder *examples.URLBuilder
}

func NewMapperImpl(URLBuilder *URLBuilder, examplesURLBuilder *examples.URLBuilder) *MapperImpl {
	return &MapperImpl{
		URLBuilder:         URLBuilder,
		examplesURLBuilder: examplesURLBuilder,
	}
}

func (c *MapperImpl) mapMainAToMainB(a0 A) (B, error) {
	return B{
		ExternalURL: c.examplesURLBuilder.Build(a0.ExternalURL),
		URL:         c.URLBuilder.Build(a0.URL),
	}, nil
}

func (c *MapperImpl) AtoB(a0 A) (B, error) {
	return c.mapMainAToMainB(a0)
}
