// Code generated by mapper, DO NOT EDIT.
package main

type MapperImpl struct{}

func NewMapperImpl() *MapperImpl {
	return &MapperImpl{}
}

func (c *MapperImpl) mapMainAToMainB(a0 A) B {
	return B{
		AnotherID: a0.ID,
		Name:      a0.MyName,
	}
}

func (c *MapperImpl) AtoB(a0 A) B {
	return c.mapMainAToMainB(a0)
}
