// Code generated by github.com/alextanhongpin/mapper, DO NOT EDIT.
package main

import examples "github.com/alextanhongpin/mapper/examples"

type MapperImpl struct {
	examplesURLer examples.URLer
	uRLer         URLer
}

func NewMapperImpl(examplesURLer examples.URLer, uRLer URLer) *MapperImpl {
	return &MapperImpl{
		examplesURLer: examplesURLer,
		uRLer:         uRLer,
	}
}

func (m *MapperImpl) mapMainAToMainB(a0 A) B {
	a0ExternalURL := m.examplesURLer.Build(a0.ExternalURL)
	a0URL := m.uRLer.Build(a0.URL)
	return B{
		ExternalURL: a0ExternalURL,
		URL:         a0URL,
	}
}

func (m *MapperImpl) AtoB(a0A A) (B, error) {
	a1A := m.mapMainAToMainB(a0A)
	return a1A, nil
}
