// Code generated by mapper, DO NOT EDIT.
package main

import examples "github.com/alextanhongpin/mapper/examples"

type MapperImpl struct {
	uRLer examples.URLer
}

func NewMapperImpl(uRLer examples.URLer) *MapperImpl {
	return &MapperImpl{uRLer: uRLer}
}

func (c *MapperImpl) mapMainAToMainB(a0 A) (B, error) {
	return B{
		ExternalURL: c.uRLer.Build(a0.ExternalURL),
		URL:         c.uRLer.Build(a0.URL),
	}, nil
}

func (c *MapperImpl) AtoB(a0 A) (B, error) {
	return c.mapMainAToMainB(a0)
}
