// Code generated by github.com/alextanhongpin/mapper, DO NOT EDIT.
package main

import examples "github.com/alextanhongpin/mapper/examples"

var _ Mapper = (*MapperImpl)(nil)

type MapperImpl struct {
	examplesURLer examples.URLer
	uRLer         URLer
}

func NewMapperImpl(examplesURLer examples.URLer, uRLer URLer) *MapperImpl {
	return &MapperImpl{
		examplesURLer: examplesURLer,
		uRLer:         uRLer,
	}
}

func (m *MapperImpl) mapMainAToMainB(g0 A) (B, error) {
	g0ExternalURL := m.examplesURLer.Build(g0.ExternalURL)
	g0URL, err := m.uRLer.Build(g0.URL)
	if err != nil {
		return B{}, err
	}
	return B{
		ExternalURL: g0ExternalURL,
		URL:         g0URL,
	}, nil
}

func (m *MapperImpl) AtoB(g0 A) (B, error) {
	g1, err := m.mapMainAToMainB(g0)
	if err != nil {
		return B{}, err
	}
	return g1, nil
}
