// Code generated by github.com/alextanhongpin/mapper, DO NOT EDIT.
package main

var _ ProductMapper = (*ProductMapperImpl)(nil)

type ProductMapperImpl struct{}

func NewProductMapperImpl() *ProductMapperImpl {
	return &ProductMapperImpl{}
}

func (p *ProductMapperImpl) mapMainProductsToMainProductSummary(p0 Products) ProductSummary {
	p0Items := CountItems(p0.Items)
	return ProductSummary{TotalCount: p0Items}
}

func (p *ProductMapperImpl) ProductToProductSummary(p0Products Products) *ProductSummary {
	p1Products := p.mapMainProductsToMainProductSummary(p0Products)
	p2Products := &p1Products
	return p2Products
}
