// Code generated by github.com/alextanhongpin/mapper, DO NOT EDIT.
package main

var _ Mapper = (*MapperImpl)(nil)

type MapperImpl struct{}

func NewMapperImpl() *MapperImpl {
	return &MapperImpl{}
}

func (m *MapperImpl) mapMainAToMainB(g0 A) B {
	return B{
		AnotherID: g0.ID,
		Name:      g0.Name,
		ToB:       g0.FromA,
	}
}

func (m *MapperImpl) AtoB(g0 A) B {
	g1 := m.mapMainAToMainB(g0)
	return g1
}
