// Code generated by mapper, DO NOT EDIT.
package main

import examples "github.com/alextanhongpin/mapper/examples"

type MapperImpl struct{}

func NewMapperImpl() *MapperImpl {
	return &MapperImpl{}
}

func (c *MapperImpl) mapMainAToMainB(a0 A) B {
	return B{
		Bool:  a0.Bool,
		ID:    a0.ID,
		Map:   a0.Map,
		Slice: a0.Slice,
		Str:   a0.Str,
	}
}

func (c *MapperImpl) mapExamplesAToExamplesB(a0 examples.A) examples.B {
	return examples.B{
		Bool:  a0.Bool,
		ID:    a0.ID,
		Map:   a0.Map,
		Slice: a0.Slice,
		Str:   a0.Str,
	}
}

func (c *MapperImpl) AtoB(a0 A) B {
	return c.mapMainAToMainB(a0)
}

func (c *MapperImpl) ExternalAtoB(a0 examples.A) examples.B {
	return c.mapExamplesAToExamplesB(a0)
}
